create triangle name "ABC"
extend "AC" to "D" with measure:"BC"
extend "BC" to "E" with measure:"AC"
create segment name "ED"
extend "ED" to "H"
extend "AB" to "H"
apply "T8" on "ad", "bc"
apply "T3" on "CED", "ABC"
apply "T6" on "ABC", "cba", "CED", "edc"
create segment name "BD"
apply "T10" on "BCD", "BC", "CD"
sum "edc" and "cdb"
sum "cba" and "dbc"
difference "edh" and "edb"
difference "abh" and "abd"